# basic options
title: Cvs
author: KaedNad(Deak Dan)
email: kaednad"gmail.com
description: Un website creat pentru a demonstra funcţionalităţile aplicaţiei Cvs.
github_username: KaedNad

# Build settings
markdown: kramdown
theme: minima
